# Info
info.application.name=@project.name@
info.application.artifactId=@project.artifactId@
info.application.version=@project.version@
info.application.description=@project.description@
info.properties.environment=${ENV:azure}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoints.jmx.exposure.include=health,info
management.info.env.enabled=true
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

# Openapi
springdoc.writer-with-order-by-keys=true
springdoc.writer-with-default-pretty-printer=true

# Server
server.servlet.context-path=/
server.port=8080

# Logging
logging.level.root=${DEFAULT_LOGGING_LEVEL:INFO}
logging.level.it.gov.pagopa=${APP_LOGGING_LEVEL:INFO}

# CORS configuration
cors.configuration=${CORS_CONFIGURATION:{"origins": ["*"], "methods": ["*"]}}

# Jackson serialization
spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# App config
mbd.payment-position.description=${MBD_PAYMENT_OPTION_DESCRIPTION:Pagamento marca da bollo digitale}
mbd.payment-position.remittance-information=${MBD_PAYMENT_OPTION_REMITTANCE_INFORMATION:Pagamento marca da bollo digitale}
mbd.payment-position.category=${MBD_PAYMENT_OPTION_CATEGORY:6/0811100IM/}
mbd.payment-position.duedate-days=${MBD_PAYMENT_OPTION_DUEDATE_DAYS:30}

# Notice number generator
notice.number.aux-digit=${NOTICE_NUMBER_AUX_DIGIT:3}
notice.number.segregation-code=${NOTICE_NUMBER_SEGREGATION_CODE:52}
notice.number.redis-key-prefix=${NOTICE_NUMBER_REDIS_KEY_PREFIX:ebollo}
notice.number.lock-millis=${NOTICE_NUMBER_LOCK_MILLIS:5000}
notice.number.max-retries=${NOTICE_NUMBER_MAX_RETRIES:7}

# redis
spring.data.redis.host=${REDIS_HOST:}
spring.data.redis.port=${REDIS_PORT:}
spring.data.redis.password=${REDIS_PASSWORD:}

# GPD client
service.gpd.host=${GPD_HOST:}
retry.gpd.maxAttempts=${RETRY_GPD_MAX_ATTEMPTS:3}
retry.gpd.maxDelay=${RETRY_GPD_MAX_DELAY:2000}

# Api Config Cache client
apiConfigCacheClient.url=${APICONFIG_CACHE_URL:}
apiConfigCacheClient.ocpSubKey=${APICONFIG_SUBKEY:}

# consumer
spring.kafka.bootstrap-servers=${CACHE_EVT_HOST:localhost:9093}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=it.gov.pagopa.*
spring.kafka.consumer.auto-offset-reset=latest
kafka.topic.nodo-dei-pagamenti-cache=${CACHE_EVT_TOPIC:nodo-dei-pagamenti-cache}
kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:pagopa-gps-mbd-service-cache-group}
spring.kafka.properties.security.protocol=${KAFKA_CONFIG_SECURITY_PROTOCOL:SASL_SSL}
spring.kafka.properties.sasl.mechanism=${KAFKA_CONFIG_SASL_MECHANISM:PLAIN}
spring.kafka.properties.sasl.jaas.config=${KAFKA_EH_CACHE_JAAS_CONFIG:}
spring.kafka.properties.session.timeout.ms=${KAFKA_CONFIG_SESSION_TIMEOUT_MS:60000}
spring.kafka.properties.request.timeout.ms=${KAFKA_CONFIG_REQUEST_TIMEOUT_MS:60000}
spring.kafka.properties.connections.max.idle.ms=${KAFKA_CONFIG_CONNECTION_MAX_IDLE_TIME:180000}
spring.kafka.properties.metadata.max.age.ms=${KAFKA_CONFIG_METADATA_MAX_AGE_INTERVAL:179000}
spring.kafka.properties.max.request.size=${KAFKA_CONFIG_METADATA_MAX_REQUEST_SIZE:1000000}