version: '3.8'

services:
  app:
    container_name: 'pagopa-gps-mbd-service'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../
      args:
        GITHUB_TOKEN_READ_PACKAGES: ${GITHUB_TOKEN_READ_PACKAGES}
    env_file:
      - ./.env
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=localhost
      - SPRING_KAFKA_LISTENER_AUTO_STARTUP=false
    ports:
      - "8080:8080"
