version: '3.8'

services:

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass secret  # <-- La password di Redis si imposta QUI!
    ports:
      - "6379:6379"

  app:
    container_name: 'pagopa-gps-mbd-service'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../
      args:
        GITHUB_TOKEN_READ_PACKAGES: ${GITHUB_TOKEN_READ_PACKAGES}
    env_file:
      - ./.env
    environment:
      # Redis Config
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=secret

      # External Clients
      - GPD_HOST=https://weudev.gps.internal.dev.platform.pagopa.it/pagopa-gpd-core
      - APICONFIG_CACHE_URL=https://weudev.apiconfig.internal.dev.platform.pagopa.it/pagopa-api-config-cache-service
      - APICONFIG_SUBKEY=mock-local-key

      # Kafka Config 
      - SPRING_KAFKA_LISTENER_AUTO_STARTUP=false
    depends_on:
      - redis
    ports:
      - "8080:8080"