version: '3.8'

secrets:
  GITHUB_TOKEN_READ_PACKAGES:
    environment: GITHUB_TOKEN_READ_PACKAGES

services:

  redis:
    image: redis:alpine@sha256:ba6e394f6acc2a695ef1b6944f161b9ca813711739be68319fa0db3470673f1d
    container_name: redis
    command: redis-server --requirepass secret
    ports:
      - "6379:6379"

  # Mock Server
  apiconfig-mock:
    image: wiremock/wiremock:latest@sha256:0d4ecb3e4dc8213fd7a4d37d6a78f6e6b553a6d2e15bd51b0999781282ac61b3
    container_name: apiconfig-mock
    ports:
      - "19091:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip"]

  app:
    container_name: 'pagopa-gps-mbd-service'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../
      secrets:
        - GITHUB_TOKEN_READ_PACKAGES
    env_file:
      - ./.env
    environment:
      # Redis Config
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=secret

      # External Clients Config
      - GPD_HOST=http://apiconfig-mock:8080
      - APICONFIG_CACHE_URL=http://apiconfig-mock:8080
      - APICONFIG_SUBKEY=mock-local-key

      # Kafka Config
      - SPRING_KAFKA_LISTENER_AUTO_STARTUP=false
    depends_on:
      - redis
      - apiconfig-mock
    ports:
      - "8080:8080"