apiVersion: v2
name: pagopa-afm-calculator
description: Microservice that handles calculation for pagoPA Advanced Fees Management
type: application
version: 0.3.0
appVersion: 1.0.2
dependencies:
  - name: microservice-chart
    version: 7.1.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
